[package]
name = "tstr"
version = "0.3.1"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition = "2024"
rust-version = "1.88.0"
license = "Zlib"
description = "type-level strings on stable"
readme="../readme.md"
documentation = "https://docs.rs/tstr"
keywords = ["no-std", "string"]
categories = ["no-std", "rust-patterns", "data-structures"]
repository = "https://github.com/rodrimati1992/tstr_crates/"
include = [
    "Cargo.toml", 
    "src/**/*.rs", 
    "LICENSE-ZLIB.md", 
    "../readme.md", 
]

[features]
default = ["const_panic"]
serde = ["dep:serde"]
str_generics = ["tstr_proc_macros/str_generics", "typewit/adt_const_marker"]
nightly_str_generics = ["str_generics"]
const_panic = ["dep:const_panic"]

use_syn = ["tstr_proc_macros/use_syn"]

# private features
docsrs = []
__ui_tests = ["trybuild"]

[dependencies.serde]
version = "1.0"
default-features = false
optional = true

[dependencies.const_panic]
version = "0.2.14"
features = ["rust_1_82"]
default-features = false
optional = true

[dev-dependencies.serde_json]
version = "1.0"

[dev-dependencies.const_panic]
version = "0.2.14"
features = ["non_basic", "rust_1_82"]
default-features = false

[dependencies.typewit]
version = "1.13"
features = ["rust_1_61"]
default-features = false

[dependencies.tstr_proc_macros]
version = "0.3.0"
path = "../tstr_proc_macros"

# no such thing as optional dev-dependencies, aaaaaaah
[dependencies.trybuild]
version = "1.0"
optional = true

[package.metadata.docs.rs]
features = ["docsrs", "const_panic", "nightly_str_generics"]






