//! This crate provides an encoding of type-level strings as types.
//!
//! # Examples
//!
//! ### Indexing
//!
//! This example demonstrates how you can use type-level strings,
//! and the [`Index`] trait, to access fields of generic types by name.
//!
//! ```
//! use std::ops::Index;
//!
//! use tstr::{TS, ts};
//!
//! fn main(){
//!     takes_person(&Person::new("Bob".into(), "Marley".into()));
//!
//!     takes_person(&OtherPerson::new("Bob", "Marley"));
//! }
//!
//! fn takes_person<P>(pers: &P)
//! where
//!     P: Index<TS!(name), Output = str> + Index<TS!(surname), Output = str>
//! {
//!     assert_eq!(&pers[ts!(name)], "Bob");
//!     assert_eq!(&pers[ts!(surname)], "Marley");
//! }
//!
//!
//! use person::Person;
//! mod person {
//!     use std::ops::Index;
//!
//!     use tstr::TS;
//!     
//!     pub struct Person {
//!         name: String,
//!         surname: String,
//!     }
//!     
//!     impl Person {
//!         pub fn new(name: String, surname: String) -> Self {
//!             Self{name, surname}
//!         }
//!     }
//!     
//!     impl Index<TS!(name)> for Person {
//!         type Output = str;
//!         
//!         fn index(&self, _: TS!(name)) -> &str {
//!             &self.name
//!         }
//!     }
//!    
//!     impl Index<TS!(surname)> for Person {
//!         type Output = str;
//!         
//!         fn index(&self, _: TS!(surname)) -> &str {
//!             &self.surname
//!         }
//!     }
//! }
//!
//! use other_person::OtherPerson;
//! mod other_person {
//!     use std::ops::Index;
//!
//!     use tstr::TS;
//!     
//!     pub struct OtherPerson {
//!         name: &'static str,
//!         surname: &'static str,
//!     }
//!     
//!     impl OtherPerson {
//!         pub fn new(name: &'static str, surname: &'static str) -> Self {
//!             Self{name, surname}
//!         }
//!     }
//!     
//!     impl Index<TS!(name)> for OtherPerson {
//!         type Output = str;
//!         
//!         fn index(&self, _: TS!(name)) -> &str {
//!             self.name
//!         }
//!     }
//!    
//!     impl Index<TS!(surname)> for OtherPerson {
//!         type Output = str;
//!         
//!         fn index(&self, _: TS!(surname)) -> &str {
//!             self.surname
//!         }
//!     }
//! }
//!
//! ```
//!
//! # Macro expansion
//!
//! This library reserves the right to change how it represent type-level strings internally
//! in every single release, and cargo feature combination.
//!
//! This only affects you if you expand the code generated by macros from this crate,
//! and then use that expanded code instead of going through the macros.
//!
//! # Cargo features
//!
//! - `"use_syn"`:
//! Changes how literals passed to the macros of this crate are parsed to use the `syn` crate.
//! Use this if there is some literal that could not be
//! parsed but is a valid str/integer literal.
//!
//! - `"str_generics"`:
//! Changes the representation of type-level strings to use a `&'static str` const parameter,
//! making for better compiler errors, and a few more features.
//! As of 2025-08-18, this feature can't be enabled, because it
//! requires `&'static str` to be stably usable as const parameters.
//! Consider using `"nightly_str_generics"` if this feature can't be used.
//!
//! - `"nightly_str_generics"`: Equivalent to the `"str_generics"` feature,
//! and enables the nightly compiler features to use `&'static str` const parameters.
//!
//! # No-std support
//!
//! This crate is unconditionally `#![no_std]`, and can be used anywhere that Rust can be.
//!
//! # Minimum Supported Rust Version
//!
//! This crate supports Rust versions back to Rust 1.88.0.
//!
//! [`Index`]: core::ops::Index
//! [`tstr::utils`]: crate::utils
#![no_std]
#![cfg_attr(feature = "nightly_str_generics", feature(adt_const_params))]
#![cfg_attr(feature = "nightly_str_generics", feature(unsized_const_params))]
#![cfg_attr(feature = "docsrs", feature(doc_cfg, doc_auto_cfg))]
#![cfg_attr(feature = "nightly_str_generics", allow(incomplete_features))]
//////////
// lints
//////////
#![allow(non_camel_case_types)]
#![forbid(unsafe_code)]

pub use typewit;

#[cfg(feature = "const_panic")]
mod assertions;

pub mod strlike;

mod macros;
mod private_macros;

mod make_trait;
mod tstr_fns;
mod tstr_trait;
mod tstr_type;

#[cfg(not(feature = "str_generics"))]
mod tstr_impl_with_chars;

#[cfg(not(feature = "str_generics"))]
pub(crate) use tstr_impl_with_chars::__TStrRepr;

#[cfg(feature = "str_generics")]
mod tstr_impl_with_str;

#[cfg(feature = "str_generics")]
pub(crate) use tstr_impl_with_str::__TStrRepr;

pub mod utils;

#[doc(hidden)]
extern crate self as tstr;

#[doc(hidden)]
pub use tstr_proc_macros::__ts_impl;

use crate::tstr_trait::__TStrArgBinary;

pub use crate::{
    make_trait::Make,
    tstr_fns::*,
    tstr_trait::{IsTStr, TStrArg},
    tstr_type::TStr,
};

include! {"./p.rs"}

#[cfg(feature = "const_panic")]
#[cfg_attr(feature = "docsrs", doc(cfg(feature = "const_panic")))]
pub use const_panic::unwrap_ok as unwrap;

#[doc(hidden)]
pub mod __p {
    pub use crate::__Empty;

    pub use const_panic::concat_panic;

    pub use core::{concat, stringify};
}
