name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        rust: [stable, beta, nightly, 1.88.0]

    steps:
    - uses: actions/checkout@v2
    - name: ci-all-versions
      run: |
        rustup override set ${{ matrix.rust }}
        cargo update
          
        cd "${{github.workspace}}/tstr_proc_macros/"
        cargo test

        cd "${{github.workspace}}/tstr/"

        cargo test --no-default-features --features ""
        cargo test --no-default-features --features "const_panic"
        cargo test --no-default-features --features "use_syn"
        cargo test --no-default-features --features "serde"
        cargo test --no-default-features --features "const_panic use_syn serde"

    - uses: actions/checkout@v2
    - name: ci-nighly
      if: ${{ matrix.rust == 'nightly' }}
      run: |
        rustup override set ${{ matrix.rust }}
        cargo update

        cd "${{github.workspace}}/tstr/"
        cargo test --no-default-features --features "nightly_str_generics "
        cargo test --no-default-features --features "nightly_str_generics const_panic"
        cargo test --no-default-features --features "nightly_str_generics use_syn"
        cargo test --no-default-features --features "nightly_str_generics serde"
        cargo test --no-default-features --features "nightly_str_generics const_panic use_syn serde"

